config:
  base_address: https://git.techpal.ru/
  auth_token: 7b7b0eddf3228937966775bea58fd03ff6c6ba58
  owner: comfortech
  tasks:
    - task:
        service: github
        name: gitub
        data_set:
          file: "all-list.json"
          max_stars: 50
        continues_update:
          enabled: true
          interval: "1d"
          multi_processing:
            enabled: true
            number_of_processes:  4
        as_private: true
        secured_data:
          enabled: 
          auth_tokens: ['','','','','','']
          issue: true
          wikis: true
          branche: true
          release: true
          label: true
          milstones: true 

