

version: '3'

services:
    redis:
        image: 'redis:5-alpine'
        environment:
            # the path of password in container
            REDIS_PASS_FILE: /run/secrets/redis-password
        command: [
            "sh", "-c",
            '
            docker-entrypoint.sh
            --requirepass "$$(cat $$REDIS_PASS_FILE)"
            '
            ]
        expose:
            - "6379"
        volumes:
            - redis-volume:/data
            # pass host password to container
            - ./.docker-compose/.redis_pass_file:/run/secrets/redis-password
        networks:
            - redis-network


volumes:
    redis-volume:

networks:
    redis-network:
        driver: bridge